plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    buildFeatures {
        buildConfig = true
    }
    namespace 'com.example.cinesound'

    compileSdk 36

    defaultConfig {
        applicationId "com.example.cinesound"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
        // ... outras configs ...
        buildConfigField "String", "TMDB_API_KEY",
                "\"" + (project.findProperty('TMDB_API_KEY') ?: '') + "\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"



    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.firebase.auth
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.runtime
    implementation libs.navigation.ui
    implementation libs.navigation.ui.ktx
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation platform('com.google.firebase:firebase-bom:34.13.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.navigation:navigation-fragment:2.7.6'
    // Material Design 3
    implementation 'com.google.android.material:material:1.11.0'
    // ConstraintLayout
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    // Navigation Component (fragments + BottomNav)
    implementation("androidx.navigation:navigation-fragment-ktx:2.7.7")
    implementation("androidx.navigation:navigation-ui-ktx:2.7.7")
    // Glide (carregamento de pôsteres)
    implementation("com.github.bumptech.glide:glide:4.16.0")
    // GridLayout (grade do catálogo)
    implementation("androidx.gridlayout:gridlayout:1.0.0")
    // CoordinatorLayout (tela de detalhes)
    implementation("androidx.coordinatorlayout:coordinatorlayout:1.2.0")

}